---
# tasks file for playbooks/roles/mount_device

- name: "Mount devices"
  with_items: "{{ devices }}"
  ansible.posix.mount:
    fstype: "{{ item.fstype }}"
    path: "{{ item.where }}"
    src: "{{ item.what }}"
    opts: "{{ item.opts | join(',') }}"
    state: "{{ item.state }}"
