---
- name: Converge
  hosts: all

  pre_tasks:

    - name: "Check if the disk file already exists"
      ansible.builtin.stat:
        path: /tmp/test_file
      register: disk_file

    - name: "Create a file to act as a disk if it doesn't exist"
      ansible.builtin.shell: |
        dd if=/dev/zero of=/tmp/test_file bs=1000000 count=100
        mkfs.ext3 /tmp/test_file
      when: not disk_file.stat.exists

  roles:
    - role: genlab.mount_device
      devices:
        - what: "/tmp/test_file"
          where: "/test_mount"
          fstype: ext3
          opts:
            - noatime
          state: mounted
