---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: "Check mountpoint"
      ansible.builtin.command:
        cmd: lsblk
      register: cmd1

    - debug:
        var: cmd1