---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: "Check mountpoint"
      ansible.builtin.command:
        cmd: mount -l
      register: mountl
      failed_when: mountl.rc != 0

    - name: "Ensure test_file is mounted on test_mount"
      ansible.builtin.assert:
        that:
           "'/tmp/test_file on /test_mount type ext3' in mountl.stdout"
